# Generated by Django 2.0.9 on 2018-10-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0002_auto_20181014_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email_address',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('email',)},
        ),
    ]
