# Generated by Django 2.0.9 on 2018-10-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('place', models.CharField(blank=True, max_length=355, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, to='ai3d.Client')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai3d.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
