# Generated by Django 2.0.9 on 2018-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0005_auto_20181023_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duration in hours', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
