# Generated by Django 2.0.9 on 2018-12-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0009_training_sign_ups_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai3d.Client'),
        ),
        migrations.AlterField(
            model_name='training',
            name='participants_limit',
            field=models.PositiveSmallIntegerField(default=20, null=True),
        ),
    ]
