# Generated by Django 2.0.9 on 2018-12-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0010_auto_20181208_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='sign_ups_closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
