# Generated by Django 2.0.9 on 2018-12-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0011_training_sign_ups_closed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='sign_ups_closed_date',
            new_name='sign_ups_close_date',
        ),
    ]
