# Generated by Django 2.2.2 on 2019-06-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0014_auto_20190629_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=355, null=True)),
                ('institution_address', models.CharField(blank=True, max_length=355, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('email', models.EmailField(max_length=70)),
                ('nip', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_applications', to='ai3d.Invoice')),
                ('participants', models.ManyToManyField(blank=True, to='ai3d.Client')),
                ('reporting_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_person', to='ai3d.Client')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_applications', to='ai3d.Training')),
            ],
        ),
    ]
