# Generated by Django 2.2.2 on 2019-06-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0015_application_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Entry',
        ),
    ]
