# Generated by Django 2.2.2 on 2019-07-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0016_auto_20190630_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_entries', to='ai3d.Entry'),
        ),
    ]
