# Generated by Django 2.2.2 on 2019-07-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0018_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
