# Generated by Django 2.2.2 on 2019-07-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0019_auto_20190702_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=250),
        ),
    ]
