# Generated by Django 2.2.2 on 2019-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0021_message_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='newsletter_agreement',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='signup_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='participants',
            field=models.ManyToManyField(blank=True, to='ai3d.Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
    ]
