# Generated by Django 2.2.2 on 2019-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0023_auto_20190728_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(),
        ),
    ]
