# Generated by Django 2.2.2 on 2019-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0024_auto_20190809_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='free_spots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
