# Generated by Django 2.2.2 on 2019-08-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai3d', '0025_training_free_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='free_spots',
        ),
    ]
